# Generated by Django 4.1 on 2022-08-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_active',
            new_name='activate',
        ),
    ]
